services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db


  yolo:
    image: tameer/yolo:0.0.1
    environment:
      - DB_BACKEND="postgres"
    ports:
      - "8081:8081"
    volumes:
      - ./uploads:/app/uploads

  ollama-ui:
    image: tameer/ollamaui:0.0.1
    ports:
      - "3000:3000"
    environment:
      - YOLO_SERVICE=yolo:8081
      - YOLO_USER=admin
      - YOLO_PASS=admin